// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK6e6Df60nzhy-M95KVYTdpzVjNF63mGY',
    appId: '1:400423479862:web:72f47bd2a571c95a02c697',
    messagingSenderId: '400423479862',
    projectId: 'uvol-project',
    authDomain: 'uvol-project.firebaseapp.com',
    storageBucket: 'uvol-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCijFZBCsM6kMRal4Sq0lJs1D8D4bH4_Kk',
    appId: '1:400423479862:android:0089f8e11860167b02c697',
    messagingSenderId: '400423479862',
    projectId: 'uvol-project',
    storageBucket: 'uvol-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4eza_Yhmtr1r_dDJh9WCS2HNEJ8gcb2Y',
    appId: '1:400423479862:ios:ba14cead663ed6cb02c697',
    messagingSenderId: '400423479862',
    projectId: 'uvol-project',
    storageBucket: 'uvol-project.firebasestorage.app',
    iosBundleId: 'com.ppkd.uvol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4eza_Yhmtr1r_dDJh9WCS2HNEJ8gcb2Y',
    appId: '1:400423479862:ios:ba14cead663ed6cb02c697',
    messagingSenderId: '400423479862',
    projectId: 'uvol-project',
    storageBucket: 'uvol-project.firebasestorage.app',
    iosBundleId: 'com.ppkd.uvol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK6e6Df60nzhy-M95KVYTdpzVjNF63mGY',
    appId: '1:400423479862:web:a51c39da5d0aed0d02c697',
    messagingSenderId: '400423479862',
    projectId: 'uvol-project',
    authDomain: 'uvol-project.firebaseapp.com',
    storageBucket: 'uvol-project.firebasestorage.app',
  );
}
